### ISSUE TITLE
"Discussion" issues should link back to the post

### ISSUE THREAD

**Issue by towerofnix** [joker314/joker314.github.io#5]
I.e., link to `joker314.github.io#(name of post)`. So that it's easier to get the context of a discussion thread.

Post article elements would need `id`s as well, but those would be just useful anyways, for linking someone to your post in general.

**Comment by joker314** [comment]
@towerofnix Thank you! Notifications now work for me!! Yay!!

**Comment by joker314** [comment]
[ ] Posts get ID numbers
[ ] These ID numbers are styled in a way I like
[ ] Issues contain links back to posts

**Comment by joker314** [comment]
@towerofnix Please confirm this resolves the issue adequately?

**Comment by joker314** [comment]
Oh, you want the names of posts to go in the hash? I think that's not a good idea because I might want to change the name of a post, and would prefer links stay permanent. *Shrugs*

**Comment by towerofnix** [comment]
Yeah, that makes sense. Just as long as the link is permanent, it's good.

**Comment by joker314** [comment]
Okay, wonderful!

**Comment by towerofnix** [comment]
And yeah, awesome! This is totally resolved.
