### ISSUE TITLE
Add I lost the game

### ISSUE THREAD

**Issue by bwbw223** [joker314/joker314.github.io#7]
^^

**Comment by joker314** [comment]
Please don't misuse the issue section of this page, thanks 😃. 

_By the way, I too did lose the game._

**Comment by joker314** [comment]
I apologise @bwbw223, I misread what you said. However, this issue is still not the best-- next time please justify why you want something added if possible. For that reason, I'm closing the issue as I deem it nonserious 👍

**Comment by bwbw223** [comment]
dude it is serious yet a joke(r314 :P)

**Comment by bwbw223** [comment]
I really need a friend now :(
